version: "3"
services:
  fpm:
    build:
      context: ./docker/fpm
    container_name: fpm
    volumes:
    - ./:/var/www
  nginx:
    container_name: http
    build:
      context: ./docker/nginx
    ports:
    - "80:80"
    volumes:
    - ./:/var/www
    - ./var/log/:/var/log
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/sites/:/etc/nginx/sites-available
    - ./docker/nginx/conf.d/:/etc/nginx/conf.d